<!DOCTYPE html>
<html>
   <head>
      <title><?php echo $title;?> - Configurando seu perfil</title>
      <meta charset="utf-8">
      <meta name="title" content="<?php echo $title;?>">
      <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
   	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
   	<meta name="msapplication-tap-highlight" content="no"/>
      <link rel="stylesheet" href="<?php echo $site_url;?>/themes/<?php echo $theme;?>/css/style.css">
      <link rel="stylesheet" href="<?php echo $site_url;?>/themes/<?php echo $theme;?>/css/screen.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript"></script>
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</head>
<body class="dashboard">
<div class="container-fluid">
<?php
include("themes/$theme/layout/dashboard/header.phtml");
?>

<div class="markup">
	<div class="align">
	<div class="flow">
	<h1>Olá <?php echo $user['nome'];?> esse aqui é o seu primeiro passo aqui no <?php echo $title;?>  escolha um desses generos para configurar seu perfil!</h1>
	<div class="confi_1">
		<div class="type">
		<span>Seu game favorito</span>
		<input type="text" name="" placeholder="Exemplo: Counter Strike Global Offensive">
		</div>
		<div class="type">
		<span>Seu filme/série/anime favorito</span>
		<input type="text" name="" placeholder="Exemplo: A rede social">
		</div>
	</div>
	</div>
	</div>
</div>



</div>
</body>