<p>Amigos sugeridos</p>

<div class="scroll">
<div class="setas">
<div class="horizon-prev">
	<p><</p>
</div>
<div class="horizon-next">
	<p>></p>
</div>
</div>
	<div class="scrolled">
		<a><img style="width: 100px; height: 100px; border-radius: 50%;" src="<?php echo $site_url;?>/themes/<?php echo $theme;?>/img/avatar/default.png"></a>
		<a><img style="width: 100px; height: 100px; border-radius: 50%;" src="<?php echo $site_url;?>/themes/<?php echo $theme;?>/img/avatar/default.png"></a>
		<a><img style="width: 100px; height: 100px; border-radius: 50%;" src="<?php echo $site_url;?>/themes/<?php echo $theme;?>/img/avatar/default.png"></a>
		<a><img style="width: 100px; height: 100px; border-radius: 50%;" src="<?php echo $site_url;?>/themes/<?php echo $theme;?>/img/avatar/default.png"></a>
		<a><img style="width: 100px; height: 100px; border-radius: 50%;" src="<?php echo $site_url;?>/themes/<?php echo $theme;?>/img/avatar/default.png"></a>
		<a><img style="width: 100px; height: 100px; border-radius: 50%;" src="<?php echo $site_url;?>/themes/<?php echo $theme;?>/img/avatar/default.png"></a>
	</div>
</div>

<style type="text/css">
	.scroll{
		width: 100%;
		height: 130px;
		background: #fff;
	}

	.scrolled{
		width: 100%;
		height: 100%;
		overflow-y: hidden;
		overflow-x: hidden;
		white-space: nowrap;
	}

	.scrolled a{
		display: inline-block;
		left: 20px;
		position: relative;
		top: 15px;
	}

	.horizon-prev{
	position: absolute;
	width: 30px;
	height: 130px;
	background: rgba(0,0,0,.50);
	top: 125px;
	z-index: 1000;
	float: left;
	left: 15px;
	cursor: pointer;
}

.horizon-prev:hover{
	background: rgba(0,0,0,.80);
}

.horizon-prev p{
	color: #fff;
	font-size: 33px;
	position: relative;
	top: 40px;
	left: 5px;
}

.horizon-next{
	position: absolute;
	width: 30px;
	height: 130px;
	background: rgba(0,0,0,.50);
	top: 125px;
	z-index: 1000;
	float: right;
	right: 10px;
	cursor: pointer;
}

.horizon-next:hover{
	background: rgba(0,0,0,.80);
}

.horizon-next p{
	color: #fff;
	font-size: 33px;
	position: relative;
	top: 40px;
	left: 5px;
}
</style>

<script type="text/javascript">

$(".setas").hide();

$('.horizon-prev').click(function() {
   event.preventDefault();
   $('.scrolled').animate({
     scrollLeft: "-=775px"
   }, "slow");
 });

  $('.horizon-next').click(function() {
   event.preventDefault();
   $('.scrolled').animate({
    scrollLeft: "+=775px"
   }, "slow");
 });

  $( ".scroll" ).hover(function(){
  	$(".setas").show();
  });

  $( ".scroll" ).mouseleave(
  function() {
  	$(".setas").hide();
  });
</script>