<div class="link-a-tab">
	<a href="/perfil/<?php echo $user['id'];?>" style="color: #fff !important; display: block;">Meu perfil</a>
	<a href="#" style="color: #fff !important; display: block;">Criar uma comunidade</a>
	<a href="#" style="color: #fff !important; display: block;">Comunidades</a>
</div>

<style type="text/css">
	.link-a-tab{
		position: relative;
		top: 0px;
		padding: 10px;
		color: #000;
		padding-right: 20px;
		margin-bottom: 0px !important;
		background: rgba(0,0,0,.40);
		border-radius: 5px;
	}

	.links-a-tab a{
		display: block !important;
	}
</style>