<div class="feed" style="top: 450px;">
	<p style="color: #000 !important; width: 100%; background: #fff; padding: 10px;">Feed de nóticias</p>

<!-- Carregar feed -->
<div class="postnews">
  <div class="title">
    <div class="title-image">
      <div class="image"></div>
    </div>
    <div class="title-content">
      <div class="title-content_content">
        <div class="line-small"></div>
        <br>
        <div class="line-medium"></div>
        <br>
        <div class="line-large"></div>
      </div>
    </div>
  </div>

  <div class="content">
    <div class="content_content">
      <div class="line-large"></div>
      <br>
      <div class="line-large"></div>
      <br>
      <div class="line-large"></div>
    </div>


  </div>
</div>
<!-- End carregar feed -->


<div class="aftercool"></div>

<div class="feedapi">
</div>



<script type="text/javascript">
//Carregar feed
$.post( "/api/listarfeed", function( data ) {
	setTimeout( function() {
  $( ".feedapi" ).html( data );
  $(".postnews").hide();
 	},3000);
});

var strangerid = <?php echo $_GET['id'];?>;

$.post("/api/listarfeed", {idstranger: strangerid},
         function(data){
        setTimeout( function() {
          $( ".feedapi" ).html( data );
          $(".postnews").hide();
        },3000);
         }
          , "html");
</script>


<style type="text/css">
	.feed{
		position: relative;
		width: 100%;
		height: auto;
		padding: 5px;
    overflow: hidden;
	}
</style>