<div class="status-p">
	<div class="back">
		<img src="<?php echo $site_url;?>/themes/<?php echo $theme;?>/img/avatar/default.png"></a>
		<p><?php echo $user['nome'];?></p>
	</div>
</div>

<style type="text/css">
	.status-p{
		width: 100%;
	    position: absolute;
	    height: 540px;
	    top: -10px;
	    text-align: center;
	    left: 0;
	}

	.status-p .back{
		width: 100%;
		position: absolute;
		height: 100%;
		background: #4a76a8;
		background-image: url("<?php echo $site_url;?>/themes/<?php echo $theme;?>/img/back.gif");
		background-size: cover;
	}

	.status-p .back img{
		position: relative;
		width: 90px;
		height: 90px;
		border-radius: 50%;
		transform: scale(1.3);
		top: 70px;
	}

	.status-p p{
		position: relative;
		top: 140px;
		color: #fff;
		transform: scale(1);
		width: 100%;
		background: #36516f;
		padding: 3px;
		font-size: 1.3em;
	}
</style>