<div class="s404notfoundpost">
  <h1 style="z-index: 10000; font-size: 1.4em; position: relative; top: 0px; text-align: center; color: #000; ">Nenhuma postagem foi encontrada, seja o primeiro a publicar :)</h1>
  <div style="position: absolute; width: 100%; height: 100%; /*background-image: url('<?php echo $site_url;?>/themes/<?php echo $theme;?>/img/404.gif');*/ background-size: cover; top: 0; left: 0;"></div>
</div>