   <div id="me" class="tabs" data-id="top">
   <div class="noti">
      <center>
      <div  class="icon" data-id="friends"><i class="fas fa-user-friends"></i></div>
      <div class="icon" data-id="search"><i class="fas fa-search"></i></div>
      <div class="icon" data-id="money"><i class="fas fa-money-bill-wave"></i></div>
      <div class="icon" data-id="settings"><i class="fas fa-cogs"></i></div>
      <div class="icon" data-id="logout"><i class="fas fa-sign-out-alt"></i></div>
      </center>
   </div>
   <div class="search">
      <input type="text" placeholder="Buscar">
      <button class="btn"><i class="fas fa-search"></i></button>
   </div>

   <div class="profile_foo" style="background: rgb(57, 63, 74); width: 100%; height: 80px; padding: 15px 0px">
      <img style="width: 80px; height: 80px; border-radius: 10px; transition: 0.4s;" src="<?php echo $avatar;?>"/>
      <span style="color: var(--white2); position: relative; top: -60px; left: 10px;"><?php echo $name_full;?></span>
   </div>

   <script type="text/javascript">
        
   </script>

</div>