<div id="feed" class="tabs" data-id="top">
   <div class="feed">
      <span><i class="fas fa-layer-group"></i>     Grupos</span>
   </div>
   <span style="color: var(--white2); padding: 10px; position: absolute; top: 40px; z-index: 2;">Sugeridos</span>
   <div class="sugered">
   	<div class="people">
   	</div>
   	<div class="people">
   	</div>
   	<div class="people">
   	</div>
   	<div class="people">
   	</div>
   </div>
</div>